name: Release

on: 
  push:
    branches:
    - master

jobs:
  build:  
   name: Release ${{ matrix.os }}
   runs-on: ${{ matrix.os }}    
   strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
   steps:
    - name: Download Repository
      uses: actions/checkout@v4    
    - name: Install Modules
      run: npm install    
    - name: Release
      run: npm run package
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}