name: Test Build

on: 
  push:
    branches:
    - master
    - dev

jobs:
  build:  
   name: Test Build ${{ matrix.os }}
   runs-on: ${{ matrix.os }}    
   strategy:
      matrix:
        os: [ubuntu-latest]
   steps:
    - name: Download Repository
      uses: actions/checkout@v2    
    - name: Install Modules
      run: npm install    
    - name: Package
      run: npm run package-all
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: |
          dist/monolith-code*
          dist/latest.yml
